services:
  mongodb:
    image: mongo:5
    restart: always
    container_name: sherpapp-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sherpMatt
      MONGO_INITDB_ROOT_PASSWORD: Mys3cretJuanan
    volumes:
      - ./mongo:/data/db

volumes:
  mongo-data:
