services:
  mongodb:
    image: mongo:5
    restart: always
    container_name: sherpapp-mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: sherpapp
    volumes:
      - ./mongo:/data/db

