version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: sherpapp-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo:/data/db

volumes:
  mongo-data:
