// src/events/user.events.ts

export const EventsList = {
  USER_LOGGED_IN: 'user.loggedIn',
  USER_REGISTERED: 'user.registered',
  USER_LOGGED_OUT: 'user.loggedOut',
  USER_UPDATED: 'user.updated',
  USER_DELETED: 'user.deleted',
  USER_EMAIL_CHANGED: 'user.emailChanged',
  USER_PASSWORD_CHANGED: 'user.passwordChanged',
  USER_PROFILE_UPDATED: 'user.profileUpdated',
  BADGE_EARNED: 'badge.earned',
  TASK_CREATED: 'task.created',
  TASK_COMPLETED: 'task.completed',
  TASK_DELETED: 'task.deleted',
  HABIT_CREATED: 'habit.created',
  HABIT_COMPLETED: 'habit.completed',
  HABIT_DELETED: 'habit.deleted',
  REMINDER_CREATED: 'reminder.created',
  REMINDER_COMPLETED: 'reminder.completed',
  POMODORO_CREATED: 'pomodoro.created',
  POMODORO_STARTED: 'pomodoro.started',
  POMODORO_COMPLETED: 'pomodoro.completed',
  POMODORO_PAUSED: 'pomodoro.paused',
  POMODORO_FINISHED: 'pomodoro.finished',
  CALENDAR_SYNCED: 'calendar.synced',
  CALENDAR_EVENT_ADDED: 'calendar.eventAdded',
  CALENDAR_EVENT_DELETED: 'calendar.eventDeleted',
  CALENDAR_TASK_ADDED: 'calendar.taskAdded',
  CALENDAR_TASK_DELETED: 'calendar.taskDeleted',
  TICKET_CREATED: 'ticket.created',
  TICKET_SOLVED: 'ticket.solved',
  RATING_SUBMITTED: 'rating.submitted',
  REVIEW_SUBMITTED: 'review.submitted',
  SUBSCRIPTION_CREATED: 'subscription.created',
  SUBSCRIPTION_CANCELED: 'subscription.canceled',
  SUBSCRIPTION_EXPIRED: 'subscription.expired',
  SUBSCRIPTION_PAYMENT_METHOD_CHANGED: 'subscription.paymentMethodChanged',
  SUBSCRIPTION_PAYMENT_METHOD_EXPIRED: 'subscription.paymentMethodExpired',
  USER_REGISTERED_GOOGLE: 'user.registeredGoogle',
  EVENT_CREATED: 'event.created',
  EVENT_DELETED: 'event.deleted',
  // Agrega más eventos según las acciones
};
